### PR TITLE
fix(provider): prefer cost_models_raw in protocol parameters

### LINKED ISSUE #303: Blockfrost provider reads legacy cost_models instead of cost_models_raw — causes ScriptIntegrityHashMismatch on Conway/Plomin
## Summary

The Blockfrost provider's `transformProtocolParameters` reads Blockfrost's legacy `cost_models` field from `/epochs/latest/parameters`. That field is an alphabetically-keyed named view. Post-Chang/Plomin (PV10), Blockfrost's named `cost_models` is both:

- **Truncated**: missing the ~53 Plutus V3 cost-model parameters added in Plomin (297 named keys vs 350 canonical integers)
- **Reordered**: alphabetical ≠ canonical Plutus-builtin index order

Any transaction with Plutus scripts ends up with a `language_view` that cannot match what the ledger computes → submit fails with `ScriptIntegrityHashMismatch`.

## Affected

- All networks post-Chang (preview / preprod / mainnet)
- Any consumer using `evoClient(chain).withBlockfrost(...)` to build transactions that carry Plutus scripts
- Verified on `preview` at epoch 1274; cost models byte-compared against Ogmios `queryLedgerState/protocolParameters`

`Koios` and `Kupmios` paths are **not** affected — they already read cost models as arrays.

## Repro

```bash
curl -s -H 'project_id: <preview_project_id>' \
  https://cardano-preview.blockfrost.io/api/v0/epochs/latest/parameters | \
  jq '{v3_named: (.cost_models.PlutusV3 | length),
       v3_raw:   (.cost_models_raw.PlutusV3 | length)}'
# => { "v3_named": 297, "v3_raw": 350 }
```

`cost_models_raw` is the canonical flat-array view Blockfrost has been returning for well over a year; it matches Ogmios byte-for-byte. `cost_models` has the Conway gap above.

## Root cause

`packages/evolution/src/sdk/provider/internal/Blockfrost.ts`:

- **L31** schema declares only `cost_models` — no `cost_models_raw`.
- **L210-213** reads `blockfrostParams.cost_models?.PlutusV*` and returns it as `Record<string, number>`.

Downstream consumers do `Object.values(costModels.PlutusV*)` on this record to build the CBOR `language_view`:

- `packages/evolution/src/sdk/builders/internal/txBuilder.ts:598-604`
- `packages/evolution/src/sdk/builders/phases/Evaluation.ts:36-41`

Alphabetically-keyed + Conway-truncated input → wrong `language_view` → wrong `script_data_hash`.

## Observed failure (real preview tx)

```
providedScriptIntegrity: 3702f2f2fad49170706bc1f04ed46b56e4111edd81d044f028da3987a3c75396
computedScriptIntegrity: 32169542440774d7f77416b62c25a887bf440e81d74e79fbc8803b50443cd8b7
```

The `provided` hash is reproducible from the 297-entry alphabetical V3 cost model; the `computed` one from the 350-entry canonical V3 cost model.

## Suggested fix

Prefer `cost_models_raw` with a fallback to `cost_models` for older Blockfrost deployments:

```ts
// In BlockfrostProtocolParameters schema (L31):
cost_models_raw: Schema.optional(
  Schema.Record({ key: Schema.String, value: Schema.Array(Schema.Number) })
),

// Replace the L210-213 inline read with:
costModels: {
  PlutusV1: costModelFromBlockfrost(blockfrostParams, "PlutusV1"),
  PlutusV2: costModelFromBlockfrost(blockfrostParams, "PlutusV2"),
  PlutusV3: costModelFromBlockfrost(blockfrostParams, "PlutusV3"),
}

// Helper:
const costModelFromBlockfrost = (
  params: BlockfrostProtocolParameters,
  lang: "PlutusV1" | "PlutusV2" | "PlutusV3"
): Record<string, number> => {
  const raw = params.cost_models_raw?.[lang]
  if (raw) return Object.fromEntries(raw.map((v, i) => [i.toString(), v]))
  return (params.cost_models?.[lang] as Record<string, number>) ?? {}
}
```

No downstream changes needed — `Object.values` on an object with numeric-string keys iterates in ascending numeric order per ECMAScript spec (integer-indexed keys), matching the canonical array order.

Verified fix against a real failing preview FES registration tx — submits successfully. Happy to open a PR.

### PR DESCRIPTION
**Pull request by solidsnakedev**
The legacy `cost_models` field from `/epochs/latest/parameters` uses alphabetically-keyed names and is truncated post-Plomin (297 entries vs 350 canonical for PlutusV3). This produces an incorrect `script_data_hash` and causes `ScriptIntegrityHashMismatch` on any transaction carrying Plutus scripts.

The provider now reads `cost_models_raw` (canonical flat arrays) instead, with a fallback to `cost_models` for older API deployments. This matches how the other providers already handle cost models.

Closes #303

### CODE REVIEW

File: packages/evolution/src/sdk/provider/internal/Blockfrost.ts [hunk 1]
```diff
@@ -187,6 +190,15 @@ export type JsonwspOgmiosEvaluationResponse = Schema.Schema.Type<typeof JsonwspO
 /**
  * Transform Blockfrost protocol parameters to Evolution SDK format
  */
+const costModelFromBlockfrost = (
+  params: BlockfrostProtocolParameters,
+  lang: "PlutusV1" | "PlutusV2" | "PlutusV3"
+): Record<string, number> => {
+  const raw = params.cost_models_raw?.[lang]
+  if (raw) return Object.fromEntries(raw.map((v, i) => [i.toString(), v]))
+  return (params.cost_models?.[lang] as Record<string, number>) ?? {}
```
Comment (mpizenberg) [inline packages/evolution/src/sdk/provider/internal/Blockfrost.ts:199]: Why doing this fallback at all if it was incorrect in the first place (as mentioned in the changeset)?
